// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    partial class accesos
    {
        public string codigo { get; set; }
        public string nombres { get; set; }
        public string clave { get; set; }
        public string caja { get; set; }
        public string almacen { get; set; }
        public string compras { get; set; }
        public string ventas { get; set; }
        public string contab { get; set; }
        public string precios { get; set; }
        public string inventario { get; set; }
        public string reparto { get; set; }
        public string asignareparto { get; set; }
        public string analisisvtas { get; set; }
        public string internet { get; set; }
        public string series { get; set; }
        public string keysql { get; set; }
        public byte tipouser { get; set; }
        public string codigvta { get; set; }
        public string abrevia { get; set; }
    }
}