// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    partial class bonificab
    {
        public int idbonifica { get; set; }
        public string proveedor { get; set; }
        public byte tipo { get; set; }
        public decimal porcada { get; set; }
        public string producto { get; set; }
        public decimal abonificar { get; set; }
        public DateTime desde { get; set; }
        public DateTime hasta { get; set; }
        public DateTime ampliacion { get; set; }
        public string descripcion { get; set; }
        public string tipoprecio { get; set; }
    }
}