// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    partial class bonifidet
    {
        public int idbonifica { get; set; }
        public string producto { get; set; }
        public decimal cantidad { get; set; }
    }
}