// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    partial class bsccabecera
    {
        public int bsc { get; set; }
        public DateTime fecha { get; set; }
        public DateTime desde { get; set; }
        public DateTime hasta { get; set; }
    }
}