// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Lider.Huacho.Model.dbModel
{
    public partial class CabCierre
    {
        public CabCierre()
        {
            cierre = new HashSet<cierre>();
        }

        public int Cabcierre1 { get; set; }
        public DateTime Fecha1 { get; set; }
        public DateTime fecha2 { get; set; }
        public string Usuario { get; set; }
        public DateTime Sysdate { get; set; }
        public string Maq { get; set; }

        public virtual ICollection<cierre> cierre { get; set; }
    }
}