// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class CABCAJA
    {
        public string TIPODOC { get; set; }
        public string NUMERO { get; set; }
        public string OPERACION { get; set; }
        public DateTime FECHA { get; set; }
        public string TIPOPER { get; set; }
        public string CODIGO { get; set; }
        public string RSOCIAL { get; set; }
        public string RUC { get; set; }
        public string DNI { get; set; }
        public string TDOCUMENTO { get; set; }
        public string NDOCUMENTO { get; set; }
        public decimal IMPORTE { get; set; }
        public string OBSERVACION { get; set; }
        public decimal TCAMBIO { get; set; }
        public string ESTADO { get; set; }
        public string CODZONA { get; set; }
        public string NOMZONA { get; set; }
        public string usuario { get; set; }
        public DateTime fechault { get; set; }
        public string concepto { get; set; }
        public byte moneda { get; set; }
        public byte formapago { get; set; }
        public string cheque { get; set; }
        public string cuenta { get; set; }
    }
}