// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class cabreq
    {
        public string requer { get; set; }
        public string proveedor { get; set; }
        public string razonsocial { get; set; }
        public DateTime? inicio { get; set; }
        public DateTime? termino { get; set; }
        public byte? estado { get; set; }
        public DateTime? fecha { get; set; }
    }
}