// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Lider.Huacho.Model.dbModel
{
    public partial class CabReparto
    {
        public CabReparto()
        {
            DetReparto = new HashSet<DetReparto>();
        }

        public string numero { get; set; }
        public DateTime fecha { get; set; }
        public string ruta { get; set; }
        public string personal { get; set; }
        public string pedido { get; set; }
        public string gestion { get; set; }
        public string zonas { get; set; }
        public string repartidor { get; set; }
        public string estado { get; set; }

        public virtual ICollection<DetReparto> DetReparto { get; set; }
    }
}