// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class canjes
    {
        public string pedido { get; set; }
        public string canje { get; set; }
        public string producto { get; set; }
        public decimal ingreso { get; set; }
        public decimal costo { get; set; }
        public decimal salida { get; set; }
        public string motivo { get; set; }
        public DateTime? fechavcto { get; set; }
        public DateTime? fecha { get; set; }
        public string estado { get; set; }
    }
}