// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class canjelet
    {
        public string tipodoc { get; set; }
        public string numero { get; set; }
        public string control { get; set; }
        public DateTime fecha { get; set; }
        public decimal monto { get; set; }
    }
}