// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class categoria
    {
        public string categoria1 { get; set; }
        public string descrip { get; set; }
        public string descripcorta { get; set; }
    }
}