// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class CHOFERES
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Licencia { get; set; }
    }
}