// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class cierre
    {
        public int Cierre1 { get; set; }
        public string personal { get; set; }
        public string periodo { get; set; }
        public decimal SaldoInicial { get; set; }
        public decimal FacContado { get; set; }
        public decimal FacCredito { get; set; }
        public decimal Cobrado { get; set; }
        public decimal Acobrado { get; set; }
        public DateTime? Fecha1 { get; set; }
        public DateTime? Fecha2 { get; set; }
        public int cabcierre { get; set; }

        public virtual CabCierre cabcierreNavigation { get; set; }
    }
}