// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class cierreopera
    {
        public DateTime fecha { get; set; }
        public string operacion { get; set; }
        public string estado { get; set; }
    }
}