// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class clase
    {
        public string clase1 { get; set; }
        public string descrip { get; set; }
        public string cuenta { get; set; }
        public string ctacargo { get; set; }
        public string ctaabono { get; set; }
    }
}