// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class ComisionLineaMarca
    {
        public string linea { get; set; }
        public string marca { get; set; }
        public decimal comimayor { get; set; }
        public decimal comimenor { get; set; }
        public decimal credmayor { get; set; }
        public decimal credmenor { get; set; }
        public decimal comiespecial { get; set; }
        public decimal comisespecial { get; set; }

        public virtual LINEA lineaNavigation { get; set; }
    }
}