// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class comisioncab
    {
        public int periodo { get; set; }
        public DateTime desde { get; set; }
        public DateTime hasta { get; set; }
        public byte dias1 { get; set; }
        public byte dias2 { get; set; }
        public byte dias3 { get; set; }
        public string estado { get; set; }
        public DateTime fcrea { get; set; }
        public string ucrea { get; set; }
        public DateTime fmodifica { get; set; }
        public string umodifica { get; set; }
    }
}