// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class compracab
    {
        public string control { get; set; }
        public string tipodoc { get; set; }
        public string numero { get; set; }
        public string orden { get; set; }
        public string proveedor { get; set; }
        public string ruc { get; set; }
        public string rsocial { get; set; }
        public string direccion { get; set; }
        public DateTime fecha { get; set; }
        public decimal nrodias { get; set; }
        public DateTime vctopago { get; set; }
        public byte moneda { get; set; }
        public decimal tcambio { get; set; }
        public decimal inafecto { get; set; }
        public decimal afecto { get; set; }
        public decimal igv { get; set; }
        public decimal total { get; set; }
        public string observa { get; set; }
        public string estado { get; set; }
        public bool ajuste { get; set; }
        public string parte { get; set; }
        public string clase { get; set; }
        public decimal pagado { get; set; }
        public decimal percepcion { get; set; }
        public decimal tigv { get; set; }

        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}