// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class concursoxcantidad_det
    {
        public int idconcurso { get; set; }
        public string producto { get; set; }
    }
}