// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class CPEEstado
    {
        public string IDDocumento { get; set; }
        public bool? Enviado { get; set; }
    }
}