// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class cuotapcab
    {
        public int idcuota { get; set; }
        public DateTime fecha { get; set; }
        public DateTime? desde { get; set; }
        public DateTime? hasta { get; set; }
        public string proveedor { get; set; }
        public string observa { get; set; }
    }
}