// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Lider.Huacho.Model.dbModel
{
    public partial class cuotagrupocab
    {
        public cuotagrupocab()
        {
            cuotagrupodet = new HashSet<cuotagrupodet>();
        }

        public int cuota { get; set; }
        public DateTime fechaini { get; set; }
        public DateTime fechafin { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public string proveedor { get; set; }

        public virtual ICollection<cuotagrupodet> cuotagrupodet { get; set; }
    }
}