// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class cuotamdet
    {
        public int idcuota { get; set; }
        public string personal { get; set; }
        public string marca { get; set; }
        public decimal importe { get; set; }
        public int cobertura { get; set; }
        public decimal porcentaje { get; set; }
    }
}