// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class cuotagrupodet
    {
        public string grupo { get; set; }
        public string personal { get; set; }
        public int cuota { get; set; }
        public decimal importe { get; set; }

        public virtual cuotagrupocab cuotaNavigation { get; set; }
        public virtual grupo grupoNavigation { get; set; }
        public virtual PERSONAL personalNavigation { get; set; }
    }
}