// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Lider.Huacho.Model.dbModel
{
    public partial class Departamento
    {
        public Departamento()
        {
            provincia = new HashSet<provincia>();
        }

        public string iddpto { get; set; }
        public string descrip { get; set; }
        public int codunilever { get; set; }

        public virtual ICollection<provincia> provincia { get; set; }
    }
}