// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class DETAGUIA
    {
        public string GuiaRemis { get; set; }
        public string Producto { get; set; }
        public decimal? Cantidad { get; set; }

        public virtual PRODUCTO ProductoNavigation { get; set; }
    }
}