// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class detinven
    {
        public string Documento { get; set; }
        public string Producto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal costo { get; set; }
        public decimal CantMalo { get; set; }
        public int orden { get; set; }

        public virtual INVENTARIO DocumentoNavigation { get; set; }
        public virtual PRODUCTO ProductoNavigation { get; set; }
    }
}