// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class DETPEDIDO
    {
        public string Pedido { get; set; }
        public string Producto { get; set; }
        public decimal PrecUnit { get; set; }
        public decimal? Cantidad { get; set; }
        public string Estado { get; set; }
        public string TipoPrecio { get; set; }
        public decimal TranGratuita { get; set; }
        public string lote { get; set; }
        public DateTime? fvctolote { get; set; }
        public string flgSurtido { get; set; }

        public virtual PEDIDO PedidoNavigation { get; set; }
        public virtual PRODUCTO ProductoNavigation { get; set; }
    }
}