// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class Distrito
    {
        public string iddistrito { get; set; }
        public string descrip { get; set; }
        public string idprovincia { get; set; }

        public virtual provincia idprovinciaNavigation { get; set; }
    }
}