// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class DOCTIPO
    {
        public string DocTipo { get; set; }
        public string Descripcion { get; set; }
        public string Serie { get; set; }
        public int? Numero { get; set; }
        public short Signo { get; set; }
        public string codigo { get; set; }
    }
}