// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class EscalaCab
    {
        public int escala { get; set; }
        public string descripcion { get; set; }
        public string proveedor { get; set; }
        public DateTime desde { get; set; }
        public DateTime hasta { get; set; }
        public DateTime ampliacion { get; set; }
        public decimal cantidadmayor { get; set; }
        public decimal cantidadmenor { get; set; }
        public decimal cantidadespecial { get; set; }
        public decimal cantidadsuperesp { get; set; }
    }
}