// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class FACTURAOTROS
    {
        public DateTime fecha { get; set; }
        public string tipodoc { get; set; }
        public string numero { get; set; }
        public string personal { get; set; }
        public string cliente { get; set; }
        public string rsocial { get; set; }
        public string direccion { get; set; }
        public string ruc { get; set; }
        public string dni { get; set; }
        public string detalle { get; set; }
        public decimal afecto { get; set; }
        public decimal inafecto { get; set; }
        public decimal igv { get; set; }
        public decimal total { get; set; }
        public decimal percepcion { get; set; }
        public string estado { get; set; }
        public string oldestado { get; set; }
    }
}