// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class faltante
    {
        public string nia { get; set; }
        public string producto { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio { get; set; }
        public decimal precunit { get; set; }
    }
}