// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Lider.Huacho.Model.dbModel
{
    public partial class FORMAPAGO
    {
        public FORMAPAGO()
        {
            PEDIDO = new HashSet<PEDIDO>();
        }

        public string FormaPago1 { get; set; }
        public string Descripcion { get; set; }
        public byte PlazoMax { get; set; }
        public byte Nrodia { get; set; }
        public bool contado { get; set; }
        public byte DiasFinta { get; set; }

        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}