// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class FuerzaVentas
    {
        public string fzavtas { get; set; }
        public string descrip { get; set; }
    }
}