// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Lider.Huacho.Model.dbModel
{
    public partial class grupo
    {
        public grupo()
        {
            cuotagrupodet = new HashSet<cuotagrupodet>();
        }

        public string grupo1 { get; set; }
        public string descrip { get; set; }
        public string descorta { get; set; }
        public string orden { get; set; }

        public virtual ICollection<cuotagrupodet> cuotagrupodet { get; set; }
    }
}