// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class gruposxproveedor
    {
        public string grupo { get; set; }
        public string descripcion { get; set; }
        public string descorta { get; set; }
        public string orden { get; set; }
    }
}