// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class GUIAREMIS
    {
        public string GuiaRemis1 { get; set; }
        public string Personal { get; set; }
        public string Estado { get; set; }
        public DateTime Fecha { get; set; }
        public string Factura1 { get; set; }
        public string Factura2 { get; set; }
        public string Boleta1 { get; set; }
        public string Boleta2 { get; set; }
        public string puntopartida { get; set; }
        public string razonsocial { get; set; }
        public string direccion { get; set; }
        public string ruc { get; set; }
        public string documentos { get; set; }

        public virtual PERSONAL PersonalNavigation { get; set; }
    }
}