// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class incentivoxcobertura_det
    {
        public int idincentivo { get; set; }
        public string producto { get; set; }
    }
}