// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class incentivoxcobertura
    {
        public int idincentivo { get; set; }
        public string titulo { get; set; }
        public DateTime desde { get; set; }
        public DateTime hasta { get; set; }
        public decimal incentivo { get; set; }
        public bool vende { get; set; }
        public string estado { get; set; }
    }
}