// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class incentivogrupo
    {
        public int idcuota { get; set; }
        public string grupo { get; set; }
        public decimal incentvolcob { get; set; }
        public decimal? incentvolmay { get; set; }
    }
}