// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class infrepartodevol
    {
        public string infreparto { get; set; }
        public string tipodoc { get; set; }
        public string documento { get; set; }
        public string producto { get; set; }
        public decimal cantidad { get; set; }
    }
}