// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class infrepartocab
    {
        public string infreparto { get; set; }
        public DateTime fecha { get; set; }
        public string ruta { get; set; }
        public string estado { get; set; }
        public string observa { get; set; }
        public string repartidor { get; set; }
        public decimal importe { get; set; }
        public string numerodevale { get; set; }
    }
}