// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class infrepartodscto
    {
        public string infreparto { get; set; }
        public string tipodoc { get; set; }
        public string documento { get; set; }
        public decimal descuento { get; set; }
    }
}