// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class INFREPARTO
    {
        public string InfReparto1 { get; set; }
        public string Documento { get; set; }
        public string TipoDoc { get; set; }
        public string TipoIng { get; set; }
        public DateTime? Fecha { get; set; }
        public decimal Valor { get; set; }
        public string Estado { get; set; }
        public decimal importe { get; set; }
        public decimal aliquidar { get; set; }
    }
}