// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class inventariocuentasdet
    {
        public string registro { get; set; }
        public string tipo { get; set; }
        public string codigo { get; set; }
        public string tipodoc { get; set; }
        public string numero { get; set; }
        public DateTime femision { get; set; }
        public DateTime fvctopago { get; set; }
        public decimal afecto { get; set; }
        public decimal inafecto { get; set; }
        public decimal igv { get; set; }
        public decimal isc { get; set; }
        public decimal total { get; set; }
        public decimal percepcion { get; set; }
        public decimal detraccion { get; set; }
        public decimal saldo { get; set; }
        public decimal pagado { get; set; }
    }
}