// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class LINEAPROVEEDOR
    {
        public string Linea { get; set; }
        public string Proveedor { get; set; }
    }
}