// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class marcasxproveedor
    {
        public string proveedor { get; set; }
        public string marca { get; set; }
        public string descripcion { get; set; }
        public string descorta { get; set; }
        public string codproveedor { get; set; }
        public string grupo { get; set; }
        public string orden { get; set; }
        public string grupounilever { get; set; }
    }
}