// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class MARCA
    {
        public string Marca { get; set; }
        public string Proveedor { get; set; }
        public string Linea { get; set; }
        public string Descripcion { get; set; }
        public string Descorta { get; set; }
        public string Orden { get; set; }

    }
}