// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class MODIDATOS
    {
        public int ModiDatos1 { get; set; }
        public string Tabla { get; set; }
        public string Campo { get; set; }
        public string ValorAntes { get; set; }
        public string ValorNuevo { get; set; }
        public string Usuario { get; set; }
        public DateTime? Fecha { get; set; }
    }
}