// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class movlotes
    {
        public string tipodoc { get; set; }
        public string documento { get; set; }
        public string producto { get; set; }
        public string lote { get; set; }
        public DateTime fechavcto { get; set; }
    }
}