// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class nlinea
    {
        public string NLINEA1 { get; set; }
        public string DESCRIPCION { get; set; }
        public double? CANMENOR { get; set; }
        public double? CANMAYOR { get; set; }
        public decimal? COMIMAYOR { get; set; }
        public decimal? COMIMENOR { get; set; }
        public decimal? CREDMAYOR { get; set; }
        public decimal? CREDMENOR { get; set; }
        public string CATEGORIA { get; set; }
        public decimal COMIESPECIAL { get; set; }
        public decimal comisespecial { get; set; }
    }
}