// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class NOTACREDITOC
    {
        public string numero { get; set; }
        public DateTime fecha { get; set; }
        public string cliente { get; set; }
        public string rsocial { get; set; }
        public string ruc { get; set; }
        public string direccion { get; set; }
        public byte tipo { get; set; }
        public string descripcion { get; set; }
        public decimal afecto { get; set; }
        public decimal inafecto { get; set; }
        public decimal? igv { get; set; }
        public decimal? total { get; set; }
        public string estado { get; set; }
        public string personal { get; set; }
        public bool contado { get; set; }
    }
}