// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class OBSERVACIONES
    {
        public string tipodoc { get; set; }
        public string documento { get; set; }
        public string numero { get; set; }
        public DateTime fecha { get; set; }
        public string observaciones1 { get; set; }
        public string resultado { get; set; }
        public string estado { get; set; }
    }
}