// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class oferta
    {
        public string oferta1 { get; set; }
        public string descripcion { get; set; }
        public DateTime desde { get; set; }
        public DateTime hasta { get; set; }
        public DateTime prorroga { get; set; }
        public string estado { get; set; }
        public string tipoprecio { get; set; }
        public string tipo { get; set; }
        public decimal cantidad { get; set; }
        public decimal tope { get; set; }
        public string producto { get; set; }
        public decimal cantidadofertada { get; set; }
        public decimal minimo { get; set; }
        public string prodminimo { get; set; }
        public decimal canminimo { get; set; }
        public decimal especial { get; set; }
        public string prodespecial { get; set; }
        public decimal canespecial { get; set; }
    }
}