// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class ordencab
    {
        public string numero { get; set; }
        public DateTime fecha { get; set; }
        public byte moneda { get; set; }
        public decimal tcambio { get; set; }
        public string proveedor { get; set; }
        public string rsocial { get; set; }
        public string observa { get; set; }
        public string operador { get; set; }
        public DateTime fechareg { get; set; }
        public string estado { get; set; }
        public byte situacion { get; set; }
    }
}