// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class PaqueteProducto
    {
        public string paquete { get; set; }
        public string producto { get; set; }
        public decimal cantidad { get; set; }
    }
}