// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class PARAMETRO
    {
        public int Parametro1 { get; set; }
        public decimal TasaIgv { get; set; }
        public decimal? TasaDolar { get; set; }
        public string Activo { get; set; }
        public decimal TopePedido { get; set; }
        public string Empresa { get; set; }
        public short DiasComision { get; set; }
        public DateTime? UltimoEnvio { get; set; }
        public string direccion { get; set; }
        public string origen { get; set; }
        public decimal minmoneda { get; set; }
        public string ruc { get; set; }
        public bool vtasinstock { get; set; }
        public bool vtasinstockp { get; set; }
        public string origen2 { get; set; }
        public bool ctacte { get; set; }
    }
}