// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class pdiversos
    {
        public string producto { get; set; }
        public string descrip { get; set; }
        public string unimed { get; set; }
        public string clase { get; set; }
        public bool conigv { get; set; }
    }
}