// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Lider.Huacho.Model.dbModel
{
    public partial class PEDIDO
    {
        public PEDIDO()
        {
            DETPEDIDO = new HashSet<DETPEDIDO>();
        }

        public string Pedido1 { get; set; }
        public string Personal { get; set; }
        public string Cliente { get; set; }
        public string FormaPago { get; set; }
        public DateTime? Fecha { get; set; }
        public string Estado { get; set; }
        public bool? Reparto { get; set; }
        public string TipoPersona { get; set; }
        public bool Procesado { get; set; }
        public string rsocial { get; set; }
        public string ruc { get; set; }
        public string direccion { get; set; }
        public string dni { get; set; }
        public string encargado { get; set; }
        public string npersonal { get; set; }
        public string nencargado { get; set; }
        public string gestion { get; set; }
        public string ptollegada { get; set; }
        public string distllegada { get; set; }
        public decimal pdscto { get; set; }
        public decimal dscto { get; set; }
        public string tipodoc { get; set; }
        public string flagCobertura { get; set; }
        public DateTime? Fecha_web { get; set; }

        public virtual FORMAPAGO FormaPagoNavigation { get; set; }
        public virtual PERSONAL PersonalNavigation { get; set; }
        public virtual ICollection<DETPEDIDO> DETPEDIDO { get; set; }
    }
}