// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Lider.Huacho.Model.dbModel
{
    public partial class PlanillaCobC
    {
        public PlanillaCobC()
        {
            PlanillaCobD = new HashSet<PlanillaCobD>();
        }

        public string numero { get; set; }
        public DateTime fecha { get; set; }
        public string personal { get; set; }
        public string zona { get; set; }
        public string npersonal { get; set; }
        public string nzona { get; set; }
        public string estado { get; set; }
        public string voucher1 { get; set; }
        public string banco1 { get; set; }
        public decimal? importe1 { get; set; }
        public string voucher2 { get; set; }
        public string banco2 { get; set; }
        public decimal? importe2 { get; set; }
        public string voucher3 { get; set; }
        public string banco3 { get; set; }
        public decimal? importe3 { get; set; }
        public string observaciones { get; set; }

        public virtual PERSONAL personalNavigation { get; set; }
        public virtual ICollection<PlanillaCobD> PlanillaCobD { get; set; }
    }
}