// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class PlanillaCobD
    {
        public string Numero { get; set; }
        public string documento { get; set; }
        public string tipodoc { get; set; }
        public decimal importe { get; set; }
        public decimal saldo { get; set; }
        public decimal? cobrado { get; set; }
        public string tipo { get; set; }
        public string DocPago { get; set; }
        public string Banco { get; set; }
        public byte Devolucion { get; set; }
        public string genera { get; set; }

        public virtual banco BancoNavigation { get; set; }
        public virtual DOCUMENTO DOCUMENTO { get; set; }
        public virtual PlanillaCobC NumeroNavigation { get; set; }
    }
}