// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class plancuen
    {
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string TIPO { get; set; }
    }
}