// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class PRODUCTO_SURTIDO
    {
        public string Producto { get; set; }
        public string Surtido { get; set; }
        public int? cantidad { get; set; }

        public virtual PRODUCTO ProductoNavigation { get; set; }
    }
}