// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class PRODUCTO
    {
        public string Producto { get; set; }
        public string Marca { get; set; }
        public string Descripcion { get; set; }
        public bool ConIgv { get; set; }
        public decimal? StockMin { get; set; }
        public decimal? StockMax { get; set; }
        public decimal StockAc { get; set; }
        public decimal? PrecMayContado { get; set; }
        public decimal? PrecMenContado { get; set; }
        public decimal? PrecMayCredito { get; set; }
        public decimal? PrecMenCredito { get; set; }
        public decimal? PrecEspecial { get; set; }
        public int? CanEspecial { get; set; }
        public string CodAlterno { get; set; }
        public decimal? Peso { get; set; }
        public decimal? Costo { get; set; }
        public string UniMed { get; set; }
        public bool Activo { get; set; }
        public short Unidades { get; set; }
        public decimal StockMal { get; set; }
        public string ean13 { get; set; }
        public string grupo { get; set; }
        public decimal stkbafecha { get; set; }
        public decimal stkmafecha { get; set; }
        public decimal comimayor { get; set; }
        public decimal comimenor { get; set; }
        public decimal credmayor { get; set; }
        public decimal credmenor { get; set; }
        public string codbase { get; set; }
        public string proveedor { get; set; }
        public string linea { get; set; }
        public string marcas { get; set; }
        public decimal minimomay { get; set; }
        public string categoria { get; set; }
        public string ncodigo { get; set; }
        public string nunimed { get; set; }
        public decimal? PrecSEspecial { get; set; }
        public bool percepcion { get; set; }
        public decimal priesgomaycon { get; set; }
        public decimal priesgomencon { get; set; }
        public decimal priesgomaycre { get; set; }
        public decimal priesgomencre { get; set; }
        public decimal costorep { get; set; }
        public decimal PrecSSEspecial { get; set; }
        public decimal comiespecial { get; set; }
        public bool? detraccion { get; set; }
        public decimal? pdetraccion { get; set; }
        public decimal? Factor { get; set; }
        public string Meta_Cant { get; set; }
        public string Meta { get; set; }
        public string Sku { get; set; }
        public int? FP { get; set; }
        public bool? StatusDms { get; set; }
        public int factorund { get; set; }
    }
}