// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class provincia
    {
        public string idprovincia { get; set; }
        public string descrip { get; set; }
        public string iddpto { get; set; }
        public int codunilever { get; set; }
        public string region { get; set; }

    }
}