// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class PROVEEDOR
    {
        public string Proveedor { get; set; }
        public string RazonSocial { get; set; }
        public string Ruc { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Ciudad { get; set; }
        public string cuenta { get; set; }
        public string nuevo { get; set; }
        public string ap_paterno { get; set; }
        public string ap_materno { get; set; }
        public string nombre1 { get; set; }
        public string nombre2 { get; set; }
        public byte clasepro { get; set; }
        public byte tipo { get; set; }
    }
}