// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class referencia
    {
        public string tipodoc { get; set; }
        public string documento { get; set; }
        public string tdrefer { get; set; }
        public string ndrefer { get; set; }
    }
}