// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class Region
    {
        public string Region1 { get; set; }
        public string Nombre { get; set; }
        public string Personal { get; set; }
    }
}