// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class REPARTO
    {
        public string Ruta { get; set; }
        public byte Dia { get; set; }
        public string Personal { get; set; }
    }
}