// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class REPARTO_PERSONAL
    {
        public string Repartidor { get; set; }
        public string Personal { get; set; }
    }
}