// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class RUTAS
    {
        public string codigo { get; set; }
        public string descripcion { get; set; }
    }
}