// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class SaldoCtaCli
    {
        public DateTime fecha { get; set; }
        public string tipodoc { get; set; }
        public string documento { get; set; }
        public string generado { get; set; }
        public DateTime femision { get; set; }
        public string cliente { get; set; }
        public string rsocial { get; set; }
        public string ruc { get; set; }
        public string dni { get; set; }
        public string direccion { get; set; }
        public decimal importe { get; set; }
        public decimal pagado { get; set; }
        public int? nrodia { get; set; }
        public string personal { get; set; }
        public string tipo { get; set; }
    }
}