// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class sku
    {
        public long sku1 { get; set; }
        public string estado { get; set; }
        public string descripcion { get; set; }
        public string nombre { get; set; }
        public string ean13 { get; set; }
        public string producto { get; set; }
        public decimal factor { get; set; }
        public decimal costo { get; set; }
    }
}