// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class spiGuiaCab
    {
        public string numero { get; set; }
        public string tipoguia { get; set; }
        public DateTime fecha { get; set; }
        public string ptopartida { get; set; }
        public string distpartida { get; set; }
        public string destinatario { get; set; }
        public string ptollegada { get; set; }
        public string ruc { get; set; }
        public string nomtransp { get; set; }
        public string ructransp { get; set; }
        public string vehiculo { get; set; }
        public string chofer { get; set; }
        public string estado { get; set; }
        public string distllegada { get; set; }
    }
}