// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class SURTIDO
    {
        public string Surtido1 { get; set; }
        public string Descripcion { get; set; }
    }
}