// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class TBL_POSICION_GRAFICOS
    {
        public long CodGrafiPos { get; set; }
        public string CodGraf { get; set; }
        public string Estado { get; set; }
        public string posicion { get; set; }
        public string CodUsuario { get; set; }
    }
}