// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class TBL_PARAM_INDICADOR
    {
        public long CodIndicador { get; set; }
        public string Indicador { get; set; }
        public string Limite_Inferior { get; set; }
        public string Limite_Superior { get; set; }
        public string Meta { get; set; }
    }
}