// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class TBL_GRUPO_BONIFICACION
    {
        public int IDRegistro { get; set; }
        public int? IDGrupoBonif { get; set; }
        public string CodProductoDesc { get; set; }
        public string TipoDescuento { get; set; }
        public int? Cantidad { get; set; }
        public int? MaxBonificacion { get; set; }
        public int? SinLimite { get; set; }
        public int? StockMes { get; set; }
        public string DescripcionBonif { get; set; }
        public bool? flag { get; set; }
    }
}