// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class TBL_MAESTRO_BONIFICACION
    {
        public int CodMaestroBonif { get; set; }
        public int? IDBonificacion { get; set; }
        public string EStado { get; set; }
        public string CodProductoBonfica { get; set; }
        public string TipoBonificacion { get; set; }
        public string DescripcionBonif { get; set; }
        public decimal? MinimoDescuento { get; set; }
        public int? EnSoles { get; set; }
        public string ProductosIncluye { get; set; }
        public string ProductosExcluye { get; set; }
        public int? IdGrupoBonificacion { get; set; }
        public DateTime? FechaActivacion { get; set; }
        public DateTime? FechaDesactivacion { get; set; }
        public string Usuario { get; set; }
        public string Comentario { get; set; }
        public string CodProductoBonfica2 { get; set; }
        public decimal? MinimoDescuento2 { get; set; }
        public bool? FlagContado { get; set; }
    }
}