// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class TBL_IDIOMA
    {
        public string CULTURE { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIPO { get; set; }
    }
}