// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class TBL_GRAFICO
    {
        public long CodGrafico { get; set; }
        public string Grafico { get; set; }
    }
}