// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class TBL_IDIOMAS
    {
        public int IDIDIOMA { get; set; }
        public string IDIOMA { get; set; }
        public string ABREV { get; set; }
    }
}