// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class TIPONEG
    {
        public string IdNegocio { get; set; }
        public string Descrip { get; set; }
        public string codunilever { get; set; }
        public string coddms { get; set; }

    }
}