// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Lider.Huacho.Model.dbModel
{
    public partial class TIPOCLI
    {
        public TIPOCLI()
        {
            CLIENTE = new HashSet<CLIENTE>();
        }

        public string TipoCli1 { get; set; }
        public string Descripcion { get; set; }
        public decimal? Porcentaje { get; set; }
        public bool Comision { get; set; }

        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
    }
}