// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class VEHICULOS
    {
        public string Placa { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public string Certin { get; set; }
        public string Configura { get; set; }
        public decimal Capacidad { get; set; }
        public decimal Volumen { get; set; }
        public byte estado { get; set; }
    }
}