// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class ZONA_PERSONAL
    {
        public string Zona { get; set; }
        public string Personal { get; set; }
        public DateTime? Dia { get; set; }
        public byte Numero { get; set; }
    }
}