// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Lider.Huacho.Model.dbModel
{
    public partial class ZONA
    {
        public string Zona { get; set; }
        public string Descripcion { get; set; }
        public int Distancia { get; set; }
        public bool Riesgo { get; set; }
        public string proveedor { get; set; }

    }
}